name: qseek_env
channels:
  - conda-forge
  - defaults
dependencies:
  - aniso8601=8.0.0
  - backoff=1.8.0
  - blinker=1.4
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.0
  - cryptography=2.8
  - fire=0.2.1
  - flask=1.1.1
  - flask-restful=0.3.7
  - flask-sqlalchemy=2.4.0
  - flask_cors=3.0.8
  - gunicorn=20.0.4
  - idna=2.9
  - itsdangerous=1.1.0
  - jinja2=2.11.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.1
  - libffi=3.2.1
  - libgfortran=4.0.0
  - liblapack=3.8.0
  - libopenblas=0.3.9
  - llvm-openmp=9.0.1
  - markupsafe=1.1.1
  - mysql-connector-c=6.1.11
  - mysqlclient=1.4.6
  - ncurses=6.1
  - numpy=1.18.1
  - oauthlib=3.0.1
  - openssl=1.1.1e
  - pandas=1.0.3
  - pip=20.0.2
  - pycparser=2.20
  - pyjwt=1.7.1
  - pymysql
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.2
  - python-dateutil=2.8.1
  - python-dotenv=0.12.0
  - python_abi=3.8
  - pytz=2019.3
  - readline=8.0
  - requests=2.23.0
  - requests-oauthlib=1.2.0
  - setuptools=45.3.0
  - six=1.14.0
  - sqlalchemy=1.3.15
  - sqlite=3.30.1
  - termcolor=1.1.0
  - tk=8.6.10
  - tweepy=3.8.0
  - urllib3=1.25.7
  - werkzeug=1.0.0
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
